import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NextAuthProvider from "@/components/other/Providers";
import { Toaster } from "react-hot-toast";
// import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import NavbarContainer from "@/components/navbar/NavbarContainer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-primary text-secondary`}
      >
        <div className="flex min-h-screen flex-col">
          <NextAuthProvider>
            <NavbarContainer />
            <main className="flex-grow">{children}</main>
            <Footer />
            <Toaster />
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
