import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/components/other/Providers";
import { Toaster } from "react-hot-toast";
// import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import NavbarContainer from "@/components/navbar/NavbarContainer";
import { cn } from "@/lib/utils";

const fontHeading = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
});

const fontBody = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cn(
          "antialiased",
          fontHeading.variable,
          fontBody.variable,
        )} bg-primary text-secondary`}
      >
        <div className="flex min-h-screen flex-col">
          <NextAuthProvider>
            <NavbarContainer />
            <main className="flex-grow">{children}</main>
            <Footer />
            <Toaster />
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
